// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209181912_initialdb")]
    partial class initialdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamentoEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EmailCliente")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estagio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Probabilidade")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefoneCliente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Visualizar Dashboard",
                            Nome = "dashboard.visualizar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Listar Projetos",
                            Nome = "projetos.listar"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Criar Projetos",
                            Nome = "projetos.criar"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Editar Projetos",
                            Nome = "projetos.editar"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Excluir Projetos",
                            Nome = "projetos.excluir"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Listar Vendas",
                            Nome = "vendas.listar"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Criar Vendas",
                            Nome = "vendas.criar"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Editar Vendas",
                            Nome = "vendas.editar"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Excluir Vendas",
                            Nome = "vendas.excluir"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Visualizar Financeiro",
                            Nome = "financeiro.visualizar"
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Criar Transações",
                            Nome = "financeiro.criar"
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Editar Transações",
                            Nome = "financeiro.editar"
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Excluir Transações",
                            Nome = "financeiro.excluir"
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Listar Usuários",
                            Nome = "usuarios.listar"
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Criar Usuários",
                            Nome = "usuarios.criar"
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Editar Usuários",
                            Nome = "usuarios.editar"
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Excluir Usuários",
                            Nome = "usuarios.excluir"
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Listar Perfis",
                            Nome = "perfis.listar"
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Criar Perfis",
                            Nome = "perfis.criar"
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Editar Perfis",
                            Nome = "perfis.editar"
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Excluir Perfis",
                            Nome = "perfis.excluir"
                        });
                });

            modelBuilder.Entity("Nexo.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Progresso")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador Total",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Acesso a vendas e projetos",
                            Nome = "Vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Acesso ao financeiro",
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("Nexo.Models.RolePermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissaoId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("RoleId", "PermissaoId")
                        .IsUnique();

                    b.ToTable("role_permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissaoId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissaoId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissaoId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissaoId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissaoId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissaoId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissaoId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissaoId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissaoId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissaoId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissaoId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissaoId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissaoId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissaoId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissaoId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissaoId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissaoId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissaoId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissaoId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissaoId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissaoId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissaoId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PermissaoId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PermissaoId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PermissaoId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            PermissaoId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            PermissaoId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            PermissaoId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            PermissaoId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 30,
                            PermissaoId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 31,
                            PermissaoId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            PermissaoId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 33,
                            PermissaoId = 13,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Nexo.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("tarefas", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DealId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("DealId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.Deal", b =>
                {
                    b.HasOne("Nexo.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Nexo.Models.Projeto", b =>
                {
                    b.HasOne("Nexo.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Nexo.Models.RolePermissao", b =>
                {
                    b.HasOne("Nexo.Models.Permissao", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexo.Models.Role", "Role")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nexo.Models.Tarefa", b =>
                {
                    b.HasOne("Nexo.Models.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexo.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projeto");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Nexo.Models.Transacao", b =>
                {
                    b.HasOne("Nexo.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexo.Models.Deal", "Deal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nexo.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");

                    b.Navigation("Deal");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Nexo.Models.Usuario", b =>
                {
                    b.HasOne("Nexo.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nexo.Models.Permissao", b =>
                {
                    b.Navigation("RolePermissoes");
                });

            modelBuilder.Entity("Nexo.Models.Projeto", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Nexo.Models.Role", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
