// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Listar usuários",
                            Nome = "usuarios.listar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Criar usuários",
                            Nome = "usuarios.criar"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Editar usuários",
                            Nome = "usuarios.editar"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Excluir usuários",
                            Nome = "usuarios.excluir"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Visualizar relatórios",
                            Nome = "relatorios.visualizar"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Gerar relatórios",
                            Nome = "relatorios.gerar"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Acessar dashboard administrativo",
                            Nome = "dashboard.admin"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Acessar dashboard de gerente",
                            Nome = "dashboard.gerente"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Acessar dashboard de usuário",
                            Nome = "dashboard.usuario"
                        });
                });

            modelBuilder.Entity("Nexo.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador do sistema com acesso total",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Gerente com permissões de gestão",
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Usuário padrão do sistema",
                            Nome = "Usuario"
                        });
                });

            modelBuilder.Entity("Nexo.Models.RolePermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissaoId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("RoleId", "PermissaoId")
                        .IsUnique();

                    b.ToTable("role_permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissaoId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissaoId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissaoId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissaoId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissaoId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissaoId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissaoId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissaoId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            PermissaoId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            PermissaoId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            PermissaoId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            PermissaoId = 9,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Nexo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Nexo.Models.RolePermissao", b =>
                {
                    b.HasOne("Nexo.Models.Permissao", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexo.Models.Role", "Role")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nexo.Models.Usuario", b =>
                {
                    b.HasOne("Nexo.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nexo.Models.Permissao", b =>
                {
                    b.Navigation("RolePermissoes");
                });

            modelBuilder.Entity("Nexo.Models.Role", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
